### ISSUE TITLE
IMPORTANT: Password Reset Implementation/Email Notification/Scheduling Bug for Milestone

### ISSUE THREAD

**Issue by gghafir** [mrjones2014/FixedIt#15] opened 2016-04-20 17:46 UTC
These issues already exist, just making sure the issue is on the top of the priority list.

**Comment by mrjones2014** [comment] 2016-04-22 17:35
Password reset system implemented - see issue #14

**Comment by mrjones2014** [comment] 2016-04-22 17:37
- [x] Password reset system
- [ ] Account creation confirmation email
- [ ] Schedule "ghosting" bug

**Comment by mrjones2014** [comment] 2016-04-28 14:07
Pretty sure the schedule ghosting bug was fixed by something we updated, I haven't experienced it in quite a while. I think it was caused by generally having numerous database and user session bugs; I think fixing those fixed the ghosting bug. Closing this issue.

**Closed by mrjones2014** 2016-04-28 14:07 UTC
Labels: help wanted
